# Generated by Django 4.2.2 on 2023-06-28 05:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание задачи')),
                ('status', models.BooleanField(default=True, verbose_name='Статус задачи')),
                ('create_date', models.DateField(default=datetime.date(2023, 6, 28), verbose_name='Дата создания')),
                ('update_date', models.DateField(default=datetime.date(2023, 6, 28), verbose_name='Дата изменения')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ('status',),
            },
        ),
    ]
